### ISSUE TITLE
badread error_model is not outputting anything and not giving an error

### ISSUE THREAD

**Issue by evantroendle** [rrwick/Badread#19]
**Describe the bug**
Hello, I have attempted to use badread to create a custom error model based on read data. I wanted to compare badread simulated samples using a custom error model to other badread simulated samples based from the included nanopore2020 error model (I also intend to create a custom qscore model).

**To reproduce**
First I have aligned to a small set of reads data before attempting to create an error profile based on more reads. I have followed the instructions to create the alignments file:
minimap2 -c -x map-ont nCoV-2019.reference.fasta Run_Name_barcode13.fastq.gz | gzip > alignments.paf.gz

To try to create an error model I have tried a few similar commands:
badread error_model --reference nCoV-2019.reference.fasta  --reads Run_Name_barcode13.fastq.gz --alignment alignments.paf.gz > new_error_model

badread error_model --reference nCoV-2019.reference.fasta  --reads Run_Name_barcode13.fastq.gz --alignment alignments.paf.gz --k_size 15 > new_error_model

#^ takes a while and the PC runs out of memory,

badread error_model --reference nCoV-2019.reference.fasta  --reads Run_Name_barcode13.fastq.gz --alignment alignments.paf.gz --k_size 2 --max_alignments 1 > new_error_model
# ^ tried to just get anything to output

files for reproducing 
[alignments.paf.gz](https://github.com/rrwick/Badread/files/9267193/alignments.paf.gz)
[nCoV-2019.reference.fasta.gz](https://github.com/rrwick/Badread/files/9267147/nCoV-2019.reference.fasta.gz)
[Run_Name_barcode13.fastq.gz](https://github.com/rrwick/Badread/files/9267148/Run_Name_barcode13.fastq.gz)

**Error message**
There is no error message (besides the case where k_size was 15 and the PC RAM couldn't support this). Any help as to what may be preventing analysis or output would be appreciated.

**System info**
 - OS: [Ubuntu 20.04]
 - Python version: [3.10.4]
 - Conda version: [4.13.0]

**Additional context**
minimap2 version: 2.17-r941
Badread v0.2.0

All the best,
Evan

**Comment by rrwick** [comment]
Thanks for pointing this out and providing files to replicate the problem. The cause was an overly stringent read length filter when loading alignments. Previously, Badread only kept alignments 1 kbp and longer (I'm used to WGS reads), but I've now reduced it to 100 bp to accomodate other cases (like amplicon sequencing): 8604542.

And a note regarding _k_ size: error model files will contain 4<sup><em>k</em></sup> lines, so I wouldn't recommend large values. The default of _k_=7 produces 16384 lines, and using _k_=15 would produce over 1 billion lines, so I'm not surprised it ran out of memory and crashed! And while _k_=2 will work, that is too small to make a good error model. I'd recommend sticking with the default of _k_=7.

Ryan
