### ISSUE TITLE
Error while processing alignments 

### ISSUE THREAD

**Issue by alihamraoui** [rrwick/Badread#25]
**Describe the bug**
Thank you for developing Badread!
I am wondering if you can advise why I get this error when trying to build a new error model?

**To reproduce**

```
fastq=dist_test_tomato_MinION.fq
fasta=genome.fa
paf_file=alignments_tomato_MinION.paf.gz

minimap2 -c -x map-ont  $fasta $fastq | gzip > $paf_file
badread error_model --reference $fasta --reads $fastq --alignment $paf_file > new_error_model
```

**Error message**
```
Processing alignments.............................................................................................................................Traceback (most recent call last):
  File "/users/depbio/hamraoui/miniconda3/envs/SLSim/bin/badread", line 10, in <module>
    sys.exit(main())
  File "/users/depbio/hamraoui/miniconda3/envs/SLSim/lib/python3.8/site-packages/badread/__main__.py", line 38, in main
    make_error_model(args, output=output)
  File "/users/depbio/hamraoui/miniconda3/envs/SLSim/lib/python3.8/site-packages/badread/error_model.py", line 62, in make_error_model
    kmer_alternatives[ref_kmer][read_kmer] += 1
KeyError: 'CCTCTNC'
```

**System info**
 - OS: 20.04
 - Python version 3.8.16

Thanks you!

**Comment by rrwick** [comment]
I'm pretty sure the problem is the `N` in your sequence. Badread assumes just `A`, `C`, `G` and `T`, so it crashed when it encountered a _k_-mer with a different letter.

The easiest solution would be to screen for reads with `N` and discard them. If that's too many reads (e.g. if most or all of your reads have an `N`), then you might need to split your reads wherever the `N`s occur.

Hope that helps! Let me know if you run into further issues.

Ryan
