### ISSUE TITLE
Explanation of output

### ISSUE THREAD

**Issue by junhaiqi** [rrwick/Badread#26]
Hello. I have the following output information of simulated data. What is the meaning of these outputs, especially 154258029-154267045 (the position of the reference sequence? But this position exceeds the length of the reference sequence)?

output：
@2dce1858-54e0-f822-d21b-c52c3d5ed39b chrX,-strand,154258029-154267045 length=1546 error-free_length=1559 read_identity=90.644%.

**Comment by rrwick** [comment]
Here's a breakdown of your read header:
* `2dce1858-54e0-f822-d21b-c52c3d5ed39b`: the read name, a random UUID.
* `chrX`: the name of the source sequence.
* `-strand`: the strand of the source sequence.
* `154258029-154267045`: the range of the source sequence which provided the read, with Pythonic (zero-based, half-open) indices. For `-strand` reads, this range refers to the reverse-complement of the source sequence.
* `length=1546`: the actual length of the read.
* `error-free_length=1559`: the length of the read before any errors were added.
* `read_identity=90.644%`: the identity of the read sequence.

My apologies regarding the confusion about the range. For circular sequences (e.g. most bacterial DNA), it's normal for the range to extend past the end. For example, a circular sequence of length 1000 could make a read that has position 950-1050, which really means position 950 to position 50, wrapping around the end.

However, I assume your sequence is linear, in which case a range past the end is indeed confusing. In this case, Badread just truncates the fragment. For example, when working with a linear sequence of length 1000, Badread may try to make a read that has position 950-1050, but since it can't loop back to the start, it will be truncated to 950-1000.

This also explains the discrepancy between your read's range and its length: the `154258029-154267045` implies a read about 9 kbp long, but your read is only 1.5 kbp long.

I've just pushed a small fix for this: bb65da0. It doesn't change anything about Badread other than how the range is printed in read headers, so no need to rerun Badread :smile:

Ryan
