### ISSUE TITLE
Error model for PacBio Kinnex RNA library

### ISSUE THREAD

**Issue by kokyriakidis** [rrwick/Badread#29]
Hi @rrwick,

Is there a way to add a model for the new PacBio Kinnex RNA data? The old PacBIo model does not seem relevant right now.

You can find some datasets here (Kinnex full-length RNA):
https://www.pacb.com/connect/datasets/

**Comment by rrwick** [comment]
You're right, that PacBio error model is very old now! Thanks for the link to the datasets. I think the [microbial one](https://downloads.pacbcloud.com/public/dataset/2021-11-Microbial-96plex) could be especially useful, because the references are probably near-perfect (or if not, I could generate near-perfect assemblies to use as references).

I'll add this to my maybe-someday to-do list :smile:

But in the meantime, you can use any of the error/qscore models (e.g. `nanopore2023`) and just tell Badread to give a very low error rate (e.g. `--identity 30,2`). That should do a good-enough job of imitating HiFi reads for many purposes.

**Comment by rrwick** [comment]
Using the microbial dataset from the link you provided, I've create new error and qscore models (`pacbio2021`) and made a new release of Badread: https://github.com/rrwick/Badread/releases/tag/v0.4.1

While I didn't train this specifically on the RNA reads you're interested in, I don't think that should matter for the purposes of Badread.
