### ISSUE TITLE
Simulate direct RNA transcript data (5' read truncation)

### ISSUE THREAD

**Issue by josiegleeson** [rrwick/Badread#36]
Is it possible to simulate reads using a transcriptome as the reference, and include some kind of distribution so that reads typically start at the correct 3' ends of transcripts, and the coverage gradually decreases toward the 5' end? 

It would be great to be able to set the read truncation rates or something at each end.

I've attached a photo of the read coverage distribution I'm after across the transcriptome. Thanks for any advice!

[sirv_rna_004.pdf](https://github.com/user-attachments/files/16901165/sirv_rna_004.pdf)

**Comment by rrwick** [comment]
Sorry, but I don't think this is possible with Badread alone.

If you're willing to do some post-processing, however, you could use Badread to simulate full-length transcript reads like this:
```
badread simulate --reference transcript_references.fasta --quantity 10x --length 100000,10000 --start_adapter_seq "" --end_adapter_seq "" --junk 0 --random 0 > reads.fastq
```
Key parameters:
* I've set the read length (`--length 100000,10000`) to be extra long (presumably longer than any of your transcripts), which will result in each read spanning the entire transcript.
* I've turned off junk and random reads (`--junk 0 --random 0`) so they don't fill up your output (with very high read lengths).
* I've turned off adapters (`--start_adapter_seq "" --end_adapter_seq ""`) because you'll be trimming the reads later anyway.

Then once you have these full-transcript reads, you could do your own processing (e.g. some kind of 5' trimming) to make the depth distribution match what your real data looks like.

Ryan

**Comment by josiegleeson** [comment]
Hi Ryan,

Ok great thank you! I was actually already trying to implement something like this but the other way around, doing pre-processing to truncate and then Badread to introduce errors. 

I might try it this way also.

Thanks for your help.

**Comment by rrwick** [comment]
That would also work!
