### ISSUE TITLE
Change install documentation

### ISSUE THREAD

**Issue by betteridiot** [rrwick/Badread#4]
**Describe the bug**
`pip3` is not guaranteed to be on every system. Therefore the note to use `pip3` for install may cause install errors. See https://github.com/rrwick/Badread/issues/2 for all output.

**To reproduce**
```bash
(base) $ conda --version
conda 4.6.8
(base) $ conda create -n badread python=3.6 --no-default-packages && conda activate badread
(badread) $ python --version
Python 3.6.7
(badread) $ pip3 install git+https://github.com/rrwick/Badread.git
Command 'pip3' not found ...
```

**Error message**
See above

**System info**
 - OS: Ubuntu 18.04.2 LTS (Bionic Beaver) on Windows Subsystem for Linux
 - Python version Python 3.6.7

**Comment by rrwick** [comment]
Thanks! Exact Python/pip commands can be tough as different ways of installing Python do things differently (e.g. pip vs pip2 vs pip3). I've added an [Installation issues](https://github.com/rrwick/Badread/wiki/Installation-issues) page to the wiki which covers all the possible pip problems I could think of (and compiler issues for #3). This page is linked to from the [installation section of the README](https://github.com/rrwick/Badread#installation).

**Comment by rrwick** [comment]
I decided to leave the [installation commands](https://github.com/rrwick/Badread#install-from-source) in the README using `pip3` instead of just `pip`. This is mainly to guard against systems with both Python 2 and 3 installed, in which case `pip` probably means `pip2`.

But if you feel strongly that `pip` would be better, I can change them to that. I would then update the [installation issues wiki page](https://github.com/rrwick/Badread/wiki/Installation-issues) to cover what to do if users run into Python version errors. Let me know what you think.

I'll be happy when Python 2 breaths its last breath and we can all just assume Python == Python 3. It will help if and when macOS switches to Python 3 🤞

**Comment by betteridiot** [comment]
No, you shouldn't need to change it. The fact that you added to the wiki is perfectly fine with me. 

P.S. I am with you on the 2.7 thing.
